"""
Superstore Profit Prediction - Machine Learning Pipeline
========================================================================
MSc Information Technology Management
Module: Machine Learning and Visualization for Data (IITG7003)
Practical Skills Assessment - "Machine Learning Business Problem Solution"
Author: Juan Osvaldo Ovalle Perez  (Student ID: Q1122568)

BUSINESS PROBLEM
----------------
A national retailer ("Superstore") wants to predict the PROFIT generated by an
order line and, more importantly, understand the drivers of profitability so it
can set smarter discounting and product-mix policies. This is framed as a
SUPERVISED REGRESSION problem (target = Profit in USD).

This single script implements the complete machine-learning lifecycle:
  1. Data loading and cleaning
  2. Feature engineering
  3. Exploratory Data Analysis (EDA) with saved visualisations
  4. Preprocessing (scaling + one-hot encoding) via scikit-learn Pipelines
  5. Model development: 5 regression algorithms with hyper-parameter tuning
  6. Model evaluation & comparison (MAE, MSE, RMSE, R^2 and 5-fold CV)
  7. Feature-importance / interpretation
  8. Export of figures, a metrics table and a Tableau-ready dataset

USAGE
-----
    python superstore_ml_pipeline.py          # run the full pipeline
    python superstore_ml_pipeline.py eda      # data prep + EDA + exports only
    python superstore_ml_pipeline.py model    # modelling + evaluation only

Outputs are written to ./figures and ./outputs.
"""

import os
import sys
import warnings
import numpy as np
import pandas as pd

import matplotlib
matplotlib.use("Agg")                 # headless backend (no display needed)
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split, GridSearchCV, cross_val_score, KFold
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

warnings.filterwarnings("ignore")

# --------------------------------------------------------------------------- #
# Global configuration
# --------------------------------------------------------------------------- #
RANDOM_STATE = 42
plt.rcParams["figure.dpi"] = 120
plt.rcParams["font.size"] = 10
plt.rcParams["axes.grid"] = True
plt.rcParams["grid.alpha"] = 0.3

PROJECT_DIR = os.path.dirname(os.path.abspath(__file__))
FIG_DIR = os.path.join(PROJECT_DIR, "figures")
OUT_DIR = os.path.join(PROJECT_DIR, "outputs")
os.makedirs(FIG_DIR, exist_ok=True)
os.makedirs(OUT_DIR, exist_ok=True)

PRIMARY, ACCENT, GREEN = "#1f4e79", "#c0504d", "#2e7d32"   # consistent palette

# Model input definition (declared once, used by the modelling stage)
TARGET = "Profit"
NUMERIC_FEATURES = ["Sales", "Quantity", "Discount", "Shipping Days", "Order Month", "Order Year"]
CATEGORICAL_FEATURES = ["Ship Mode", "Segment", "Region", "Category", "Sub-Category"]


def savefig(fig, name):
    """Save a figure to the figures directory and close it."""
    fig.tight_layout()
    fig.savefig(os.path.join(FIG_DIR, name), bbox_inches="tight")
    plt.close(fig)
    print(f"  [figure] {name}")


def find_dataset():
    """Locate the Superstore CSV in common relative locations."""
    candidates = [
        os.path.join(PROJECT_DIR, "data", "Sample - Superstore.csv"),
        os.path.join(PROJECT_DIR, "Sample - Superstore.csv"),
        os.path.join(os.path.dirname(PROJECT_DIR), "Sample - Superstore.csv"),
    ]
    for c in candidates:
        if os.path.exists(c):
            return c
    raise FileNotFoundError("Sample - Superstore.csv not found in data/ or project root.")


# =========================================================================== #
# 1 + 2.  DATA LOADING, CLEANING & FEATURE ENGINEERING
# =========================================================================== #
def get_data():
    """Load, clean and feature-engineer the Superstore dataset."""
    print("\n[1] Loading and cleaning data ...")
    path = find_dataset()
    df = pd.read_csv(path, encoding="latin-1")
    print(f"  Loaded {df.shape[0]} rows x {df.shape[1]} columns from '{os.path.basename(path)}'")

    # Parse the date columns (source format is M/D/Y, e.g. 11/8/2016)
    df["Order Date"] = pd.to_datetime(df["Order Date"], format="%m/%d/%Y", errors="coerce")
    df["Ship Date"] = pd.to_datetime(df["Ship Date"], format="%m/%d/%Y", errors="coerce")

    print(f"  Missing values: {int(df.isna().sum().sum())} | "
          f"Duplicate rows: {int(df.duplicated().sum())}")
    df = df.drop_duplicates().reset_index(drop=True)

    print("\n[2] Engineering features ...")
    df["Shipping Days"] = (df["Ship Date"] - df["Order Date"]).dt.days
    df["Order Year"] = df["Order Date"].dt.year
    df["Order Month"] = df["Order Date"].dt.month
    df["Order Quarter"] = df["Order Date"].dt.quarter
    df["Profit Margin"] = df["Profit"] / df["Sales"]        # analytical field (NOT a model input)
    df["Is Profitable"] = (df["Profit"] > 0).astype(int)    # analytical flag
    print("  Added: Shipping Days, Order Year/Month/Quarter, Profit Margin, Is Profitable")
    return df


# =========================================================================== #
# 3.  EXPLORATORY DATA ANALYSIS  (+ Tableau export)
# =========================================================================== #
def run_eda(df):
    print("\n[3] Exploratory data analysis ...")
    total_sales = df["Sales"].sum()
    total_profit = df["Profit"].sum()
    overall_margin = total_profit / total_sales
    pct_unprofitable = 100 * (df["Profit"] < 0).mean()

    profit_by_cat = df.groupby("Category")["Profit"].sum().sort_values(ascending=False)
    profit_by_subcat = df.groupby("Sub-Category")["Profit"].sum().sort_values()
    profit_by_region = df.groupby("Region")["Profit"].sum().sort_values(ascending=False)
    profit_by_segment = df.groupby("Segment")["Profit"].sum().sort_values(ascending=False)
    disc_profit_corr = df["Discount"].corr(df["Profit"])
    disc_margin_corr = df["Discount"].corr(df["Profit Margin"])

    with open(os.path.join(OUT_DIR, "eda_summary.txt"), "w") as f:
        f.write("SUPERSTORE EDA SUMMARY\n======================\n")
        f.write(f"Records: {len(df)}\n")
        f.write(f"Date range: {df['Order Date'].min().date()} to {df['Order Date'].max().date()}\n")
        f.write(f"Total sales: ${total_sales:,.2f}\n")
        f.write(f"Total profit: ${total_profit:,.2f}\n")
        f.write(f"Overall profit margin: {overall_margin:.2%}\n")
        f.write(f"Share of loss-making order lines: {pct_unprofitable:.1f}%\n")
        f.write(f"Mean profit/line: ${df['Profit'].mean():.2f} | Median: ${df['Profit'].median():.2f}\n")
        f.write(f"Discount-Profit correlation: {disc_profit_corr:.3f}\n")
        f.write(f"Discount-Profit Margin correlation: {disc_margin_corr:.3f}\n\n")
        f.write("Profit by Category:\n" + profit_by_cat.to_string() + "\n\n")
        f.write("Profit by Sub-Category (ascending):\n" + profit_by_subcat.to_string() + "\n\n")
        f.write("Profit by Region:\n" + profit_by_region.to_string() + "\n\n")
        f.write("Profit by Segment:\n" + profit_by_segment.to_string() + "\n")
    print(f"  Total sales=${total_sales:,.0f} | Total profit=${total_profit:,.0f} | "
          f"Margin={overall_margin:.1%} | Loss-making lines={pct_unprofitable:.1f}%")
    print(f"  Discount-Profit corr={disc_profit_corr:.3f} | Discount-Margin corr={disc_margin_corr:.3f}")
    print(f"  Worst 3 sub-categories: {list(profit_by_subcat.head(3).index)}")
    print(f"  Best 3 sub-categories : {list(profit_by_subcat.tail(3).index)}")

    # Fig 1: distributions of Sales and Profit
    fig, ax = plt.subplots(1, 2, figsize=(11, 4))
    ax[0].hist(df["Sales"], bins=60, color=PRIMARY)
    ax[0].set(title="Distribution of Sales", xlabel="Sales (USD)", ylabel="Frequency", xlim=(0, 2000))
    ax[1].hist(df["Profit"], bins=80, color=ACCENT)
    ax[1].axvline(0, color="black", lw=1)
    ax[1].set(title="Distribution of Profit", xlabel="Profit (USD)", ylabel="Frequency", xlim=(-600, 600))
    savefig(fig, "fig01_target_distribution.png")

    # Fig 2: total profit by category
    fig, ax = plt.subplots(figsize=(7, 4))
    ax.bar(profit_by_cat.index, profit_by_cat.values,
           color=[GREEN if v >= 0 else ACCENT for v in profit_by_cat.values])
    ax.set(title="Total Profit by Category", ylabel="Profit (USD)")
    savefig(fig, "fig02_profit_by_category.png")

    # Fig 3: total profit by sub-category (loss-makers visible)
    fig, ax = plt.subplots(figsize=(8, 6))
    ax.barh(profit_by_subcat.index, profit_by_subcat.values,
            color=[GREEN if v >= 0 else ACCENT for v in profit_by_subcat.values])
    ax.axvline(0, color="black", lw=1)
    ax.set(title="Total Profit by Sub-Category", xlabel="Profit (USD)")
    savefig(fig, "fig03_profit_by_subcategory.png")

    # Fig 4: mean profit by discount level
    disc_grp = df.groupby("Discount")["Profit"].mean()
    fig, ax = plt.subplots(figsize=(7, 4))
    ax.bar(disc_grp.index.astype(str), disc_grp.values,
           color=[GREEN if v >= 0 else ACCENT for v in disc_grp.values])
    ax.axhline(0, color="black", lw=1)
    ax.set(title="Mean Profit by Discount Level", xlabel="Discount", ylabel="Mean Profit (USD)")
    plt.setp(ax.get_xticklabels(), rotation=45, ha="right")
    savefig(fig, "fig04_discount_vs_profit.png")

    # Fig 5: correlation heatmap (numeric variables)
    num_cols = ["Sales", "Quantity", "Discount", "Profit", "Shipping Days", "Profit Margin"]
    corr = df[num_cols].corr()
    fig, ax = plt.subplots(figsize=(6.5, 5.5))
    im = ax.imshow(corr, cmap="RdBu_r", vmin=-1, vmax=1)
    ax.set_xticks(range(len(num_cols))); ax.set_xticklabels(num_cols, rotation=45, ha="right")
    ax.set_yticks(range(len(num_cols))); ax.set_yticklabels(num_cols)
    for i in range(len(num_cols)):
        for j in range(len(num_cols)):
            ax.text(j, i, f"{corr.iloc[i, j]:.2f}", ha="center", va="center",
                    color="white" if abs(corr.iloc[i, j]) > 0.5 else "black", fontsize=9)
    fig.colorbar(im, fraction=0.046, pad=0.04)
    ax.set_title("Correlation Matrix (numeric variables)")
    savefig(fig, "fig05_correlation_heatmap.png")

    # Fig 6: sales & profit by region
    reg = df.groupby("Region")[["Sales", "Profit"]].sum().sort_values("Sales", ascending=False)
    fig, ax = plt.subplots(figsize=(7, 4))
    x = np.arange(len(reg)); w = 0.38
    ax.bar(x - w/2, reg["Sales"], w, label="Sales", color=PRIMARY)
    ax.bar(x + w/2, reg["Profit"], w, label="Profit", color=GREEN)
    ax.set_xticks(x); ax.set_xticklabels(reg.index)
    ax.set(title="Sales and Profit by Region", ylabel="USD"); ax.legend()
    savefig(fig, "fig06_sales_profit_by_region.png")

    # Fig 7: monthly sales & profit trend
    ts = df.set_index("Order Date").resample("ME")[["Sales", "Profit"]].sum()
    fig, ax = plt.subplots(figsize=(10, 4))
    ax.plot(ts.index, ts["Sales"], label="Sales", color=PRIMARY)
    ax.plot(ts.index, ts["Profit"], label="Profit", color=GREEN)
    ax.set(title="Monthly Sales and Profit (2014-2017)", ylabel="USD"); ax.legend()
    savefig(fig, "fig07_monthly_trend.png")

    # Tableau-ready export (re-used by the Project Output / Tableau assignment)
    tableau_cols = ["Order Date", "Ship Date", "Ship Mode", "Segment", "Region", "State", "City",
                    "Category", "Sub-Category", "Sales", "Quantity", "Discount", "Profit",
                    "Shipping Days", "Order Year", "Order Month", "Order Quarter",
                    "Profit Margin", "Is Profitable"]
    df[tableau_cols].to_csv(os.path.join(OUT_DIR, "superstore_clean_for_tableau.csv"), index=False)
    print("  Saved outputs/eda_summary.txt and outputs/superstore_clean_for_tableau.csv")


# =========================================================================== #
# 4-7.  MODELLING, EVALUATION & INTERPRETATION
# =========================================================================== #
def run_modeling(df):
    print("\n[4] Building preprocessing pipeline ...")
    model_df = df[NUMERIC_FEATURES + CATEGORICAL_FEATURES + [TARGET]].dropna().copy()

    # Outlier handling (Task 2): Sales and Profit are highly right/left-skewed with
    # extreme tails. We winsorise both monetary variables at the 1st/99th percentiles
    # so that a handful of exceptional transactions do not dominate the squared-error
    # loss and destabilise hold-out evaluation. ~2% of values are capped; the extreme
    # transactions remain visible in the (un-capped) EDA.
    for col in ["Sales", "Profit"]:
        lo, hi = model_df[col].quantile([0.01, 0.99])
        n_out = int(((model_df[col] < lo) | (model_df[col] > hi)).sum())
        model_df[col] = model_df[col].clip(lo, hi)
        print(f"  Winsorised {col} to [{lo:.2f}, {hi:.2f}] ({n_out} values capped)")

    X = model_df[NUMERIC_FEATURES + CATEGORICAL_FEATURES]
    y = model_df[TARGET]
    print(f"  Modelling matrix: {X.shape[0]} rows, {len(NUMERIC_FEATURES)} numeric + "
          f"{len(CATEGORICAL_FEATURES)} categorical features")

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.20, random_state=RANDOM_STATE)
    print(f"  Train: {X_train.shape[0]} | Test: {X_test.shape[0]} (80/20 split)")

    preprocess = ColumnTransformer([
        ("num", StandardScaler(), NUMERIC_FEATURES),
        ("cat", OneHotEncoder(handle_unknown="ignore"), CATEGORICAL_FEATURES),
    ])

    print("\n[5] Training and tuning models ...")
    # Every model is wrapped in GridSearchCV (with >=1 candidate) so a single fit
    # yields BOTH the tuned estimator and the per-fold cross-validation scores,
    # avoiding redundant re-fitting. Grids are deliberately lean for runtime while
    # remaining representative of standard practice.
    models = {
        "Linear Regression": (LinearRegression(), {"m__fit_intercept": [True]}),
        "Ridge Regression": (Ridge(random_state=RANDOM_STATE), {"m__alpha": [1.0, 10.0, 100.0]}),
        "Lasso Regression": (Lasso(random_state=RANDOM_STATE, max_iter=5000), {"m__alpha": [0.1, 1.0, 10.0]}),
        "Random Forest": (RandomForestRegressor(random_state=RANDOM_STATE, n_jobs=-1),
                          {"m__n_estimators": [120], "m__max_depth": [None, 20]}),
        "Gradient Boosting": (GradientBoostingRegressor(random_state=RANDOM_STATE, max_depth=3),
                              {"m__n_estimators": [100], "m__learning_rate": [0.1]}),
    }

    cv = KFold(n_splits=5, shuffle=True, random_state=RANDOM_STATE)
    results, fitted, cv_scores = [], {}, {}

    for name, (estimator, grid) in models.items():
        pipe = Pipeline([("prep", preprocess), ("m", estimator)])
        gs = GridSearchCV(pipe, grid, scoring="r2", cv=cv, n_jobs=-1)
        gs.fit(X_train, y_train)
        best, best_params = gs.best_estimator_, gs.best_params_

        # Per-fold CV R^2 for the winning hyper-parameter combination
        bi = gs.best_index_
        folds = np.array([gs.cv_results_[f"split{i}_test_score"][bi] for i in range(cv.get_n_splits())])

        pred = best.predict(X_test)
        mae = mean_absolute_error(y_test, pred)
        mse = mean_squared_error(y_test, pred)
        rmse = float(np.sqrt(mse))
        r2 = r2_score(y_test, pred)

        shown = {k: v for k, v in best_params.items() if k != "m__fit_intercept"}
        results.append({"Model": name, "MAE": round(mae, 3), "MSE": round(mse, 2),
                        "RMSE": round(rmse, 3), "R2": round(r2, 4),
                        "CV_R2_mean": round(folds.mean(), 4), "CV_R2_std": round(folds.std(), 4),
                        "Best_Params": str(shown)})
        fitted[name] = best
        cv_scores[name] = folds
        print(f"  {name:<20} R2={r2:0.3f}  RMSE={rmse:7.2f}  MAE={mae:6.2f}  "
              f"CV_R2={folds.mean():0.3f}+/-{folds.std():0.3f}  params={shown}")

    res_df = pd.DataFrame(results).sort_values("R2", ascending=False).reset_index(drop=True)
    res_df.to_csv(os.path.join(OUT_DIR, "model_metrics.csv"), index=False)
    best_name = res_df.iloc[0]["Model"]
    best_model = fitted[best_name]
    print(f"\n  >>> Best model: {best_name} (R2={res_df.iloc[0]['R2']:.3f})")

    print("\n[6] Producing evaluation figures ...")
    # Fig 8: model comparison (R2 and RMSE)
    fig, ax = plt.subplots(1, 2, figsize=(12, 4.5))
    o1 = res_df.sort_values("R2")
    ax[0].barh(o1["Model"], o1["R2"], color=PRIMARY); ax[0].set(title="Test R² by Model", xlabel="R²")
    o2 = res_df.sort_values("RMSE", ascending=False)
    ax[1].barh(o2["Model"], o2["RMSE"], color=ACCENT); ax[1].set(title="Test RMSE by Model", xlabel="RMSE (USD)")
    savefig(fig, "fig08_model_comparison.png")

    # Fig 9: actual vs predicted (best model)
    pred_best = best_model.predict(X_test)
    fig, ax = plt.subplots(figsize=(6, 6))
    ax.scatter(y_test, pred_best, s=8, alpha=0.3, color=PRIMARY)
    lims = [min(y_test.min(), pred_best.min()), max(y_test.max(), pred_best.max())]
    ax.plot(lims, lims, color=ACCENT, lw=1.5)
    ax.set(title=f"Actual vs Predicted Profit - {best_name}",
           xlabel="Actual Profit (USD)", ylabel="Predicted Profit (USD)")
    savefig(fig, "fig09_actual_vs_predicted.png")

    # Fig 10: residual distribution
    resid = y_test - pred_best
    fig, ax = plt.subplots(figsize=(7, 4))
    ax.hist(resid, bins=80, color=PRIMARY); ax.axvline(0, color=ACCENT, lw=1.5)
    ax.set(title=f"Residuals - {best_name}", xlabel="Residual (USD)", ylabel="Frequency", xlim=(-400, 400))
    savefig(fig, "fig10_residuals.png")

    # Fig 11: feature importance / coefficients (best model)
    ohe = best_model.named_steps["prep"].named_transformers_["cat"]
    feat_names = NUMERIC_FEATURES + list(ohe.get_feature_names_out(CATEGORICAL_FEATURES))
    estimator = best_model.named_steps["m"]
    if hasattr(estimator, "feature_importances_"):
        imp, imp_label = estimator.feature_importances_, "Feature Importance"
    else:
        imp, imp_label = np.abs(estimator.coef_), "|Coefficient|"
    imp_series = pd.Series(imp, index=feat_names).sort_values(ascending=False).head(15)
    fig, ax = plt.subplots(figsize=(8, 6))
    ax.barh(imp_series.index[::-1], imp_series.values[::-1], color=PRIMARY)
    ax.set(title=f"Top 15 Predictors - {best_name}", xlabel=imp_label)
    savefig(fig, "fig11_feature_importance.png")

    # Fig 12: 5-fold cross-validation R2 distribution
    fig, ax = plt.subplots(figsize=(8, 4.5))
    names = list(cv_scores.keys())
    ax.boxplot([cv_scores[n] for n in names])
    ax.set_xticks(range(1, len(names) + 1)); ax.set_xticklabels(names, rotation=20, ha="right")
    ax.set(title="5-Fold Cross-Validation R² by Model", ylabel="R²")
    savefig(fig, "fig12_cv_scores.png")

    print("\n================= MODEL COMPARISON =================")
    print(res_df[["Model", "MAE", "RMSE", "R2", "CV_R2_mean", "CV_R2_std"]].to_string(index=False))
    print("===================================================")


# =========================================================================== #
# Entry point
# =========================================================================== #
def main():
    stage = sys.argv[1].lower() if len(sys.argv) > 1 else "all"
    df = get_data()
    if stage in ("all", "eda"):
        run_eda(df)
    if stage in ("all", "model"):
        run_modeling(df)
    print("\n===PIPELINE COMPLETE===")


if __name__ == "__main__":
    main()
